services:
  graphql-service:
    container_name: graphql-service
    build: ./graphql-api
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network
#
#  grpc-service:
#    build: ./grpc-api
#    ports:
#      - "8082:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#    depends_on:
#      - db
#    networks:
#      - app-network

  rest-service:
    container_name: rest-service
    build: ./rest-api
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./api-comparison
    ports:
      - "80:80"
    depends_on:
#      - graphql-service
#      - grpc-service
      - rest-service
    networks:
      - app-network

  db:
    container_name: database
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge